### ISSUE TITLE
Map container height fix

### ISSUE THREAD

**Issue by pablohpsilva** [starkland/veggiemap#14]
Add the following rule to remove page scrolling. It will "fix" the nav on top

```css
.map-container {
  height: calc(100% - 49px);
}
```
